// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVG0R9y-k7Rs9Fuj9DdXTiDdbnPKYzuuU',
    appId: '1:933296166185:web:0cc447dadf3e3887a91338',
    messagingSenderId: '933296166185',
    projectId: 'wifiguard-ecb9b',
    authDomain: 'wifiguard-ecb9b.firebaseapp.com',
    databaseURL: 'https://wifiguard-ecb9b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wifiguard-ecb9b.firebasestorage.app',
    measurementId: 'G-MNCYGDPCYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp0wpW8jbDQSYw9uY5F9qH-9PE6m1cY3A',
    appId: '1:933296166185:android:06466174a05cf0c1a91338',
    messagingSenderId: '933296166185',
    projectId: 'wifiguard-ecb9b',
    databaseURL: 'https://wifiguard-ecb9b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wifiguard-ecb9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGf6INz4w4dBjh13zeBf_paK6pClBNjqU',
    appId: '1:933296166185:ios:b91c9a95df75fbbea91338',
    messagingSenderId: '933296166185',
    projectId: 'wifiguard-ecb9b',
    databaseURL: 'https://wifiguard-ecb9b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wifiguard-ecb9b.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGf6INz4w4dBjh13zeBf_paK6pClBNjqU',
    appId: '1:933296166185:ios:b91c9a95df75fbbea91338',
    messagingSenderId: '933296166185',
    projectId: 'wifiguard-ecb9b',
    databaseURL: 'https://wifiguard-ecb9b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wifiguard-ecb9b.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVG0R9y-k7Rs9Fuj9DdXTiDdbnPKYzuuU',
    appId: '1:933296166185:web:97bceb57232bd4f8a91338',
    messagingSenderId: '933296166185',
    projectId: 'wifiguard-ecb9b',
    authDomain: 'wifiguard-ecb9b.firebaseapp.com',
    databaseURL: 'https://wifiguard-ecb9b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wifiguard-ecb9b.firebasestorage.app',
    measurementId: 'G-2JBDYXNQYS',
  );
}
